export const Mutation = {
  UP_STEP_COUNTER: "UP_STEP_COUNTER",
  DOWN_STEP_COUNTER: "DOWN_STEP_COUNTER",
  UP_STEP_PROGRESS_BAR: "UP_STEP_PROGRESS_BAR",
  DOWN_STEP_PROGRESS_BAR: "DOWN_STEP_PROGRESS_BAR",
  SET_EMAIL: "SET_EMAIL",
  SET_FIRST_NAME: "SET_FIRST_NAME",
  SET_LAST_NAME: "SET_LAST_NAME",
  SET_GENDER: "SET_GENDER",
  SET_COMPANY: "SET_COMPANY",
  SET_TIME_ZONE: "SET_TIME_ZONE",
  SET_DATA_ACCOUNT: "SET_DATA_ACCOUNT",
  REMOVE_EMPTY_DATA: "REMOVE_EMPTY_DATA",
  UPDATE_ERROR_MESSAGE: "UPDATE_ERROR_MESSAGE"
};

export const Action = {
  VALIDATE_EMAIL: "VALIDATE_EMAIL",
  VALIDATE_TEXT_INPUT: "VALIDATE_TEXT_INPUT",
  IS_EMAIL_RESERVED: "IS_EMAIL_RESERVED",
  UP_STEP: "UP_STEP",
  DOWN_STEP: "DOWN_STEP",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  LOAD_DATA_ACCOUNT: "LOAD_DATA_ACCOUNT"
};
